# Generated by Django 5.1.6 on 2025-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی معرف')),
                ('introducer_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن معرف')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('family_members', models.IntegerField(blank=True, null=True, verbose_name='تعداد اعضای تحت سرپرستی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت تاهل')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='مذهب')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('is_covered', models.BooleanField(blank=True, default=False, null=True, verbose_name='تحت پوشش')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='خیابان')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
