# Generated by Django 5.1.6 on 2025-02-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='is_covered',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تحت پوشش'),
        ),
    ]
