# Generated by Django 5.1.3 on 2025-03-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0004_needy_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='path',
            field=models.CharField(blank=True, choices=[('تعریف نشده', 'تعریف نشده'), ('1', 'مسیر 1'), ('2', 'مسیر 2'), ('3', 'مسیر 3'), ('4', 'مسیر 4'), ('5', 'مسیر 5'), ('6', 'مسیر 6'), ('7', 'مسیر 7'), ('8', 'مسیر 8'), ('9', 'مسیر 9'), ('10', 'مسیر 10')], max_length=15, null=True, verbose_name='مسیر'),
        ),
    ]
