# Generated by Django 5.1.6 on 2025-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0005_alter_needy_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='is_covered',
            field=models.CharField(blank=True, choices=[('بدون پوشش', 'بدون پوشش'), ('کمیته امداد', 'کمیته امداد'), ('بهزیستی', 'بهزیستی'), ('کمیته امداد و بهزیستی', 'کمیته امداد و بهزیستی')], max_length=100, null=True, verbose_name='تحت پوشش'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل'), ('متارکه', 'متارکه')], max_length=20, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='religion',
            field=models.CharField(blank=True, choices=[('شیعه', 'شیعه'), ('سنی', 'سنی')], max_length=50, null=True, verbose_name='مذهب'),
        ),
    ]
