# Generated by Django 5.1.6 on 2025-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0006_alter_needy_is_covered_alter_needy_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=100, null=True)),
            ],
        ),
    ]
