# Generated by Django 5.1.6 on 2025-03-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0007_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='street',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='needy.street', verbose_name='خیابان'),
        ),
    ]
