# Generated by Django 5.1.6 on 2025-03-06 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0008_alter_needy_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='house_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='needy',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='needy',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت جغرافیایی'),
        ),
        migrations.AddField(
            model_name='needy',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک موقعیت مکانی در نشان'),
        ),
        migrations.AddField(
            model_name='needy',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='path',
            field=models.CharField(blank=True, choices=[('تعریف نشده', 'تعریف نشده'), ('1', 'مسیر 1'), ('2', 'مسیر 2'), ('3', 'مسیر 3'), ('4', 'مسیر 4'), ('5', 'مسیر 5'), ('6', 'مسیر 6'), ('7', 'مسیر 7'), ('8', 'مسیر 8'), ('9', 'مسیر 9'), ('10', 'مسیر 10')], default=1, max_length=15, null=True, verbose_name='مسیر'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خیابان'),
        ),
        migrations.CreateModel(
            name='NeedyPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مسیر')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='needy.street', verbose_name='خیابان مربوطه')),
            ],
        ),
    ]
