# Generated by Django 5.1.6 on 2025-03-06 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0009_needy_house_number_needy_latitude_needy_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='path',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='needy.needypath', verbose_name='مسیر'),
        ),
    ]
