# Generated by Django 5.1.6 on 2025-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0010_alter_needy_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='needy',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت جغرافیایی'),
        ),
        migrations.AddField(
            model_name='needy',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک موقعیت مکانی در نشان'),
        ),
        migrations.AddField(
            model_name='needy',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='house_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='پلاک'),
        ),
    ]
